import React from 'react';
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import cardStyles from '../styles/Cards.module.css'

import pokemon from 'pokemontcgsdk'

export default function Home() {
  const [cards, setCards] = React.useState([])

  React.useEffect(() => {
    
    pokemon.card.where({ pageSize: 30, page: 1 })
    .then(result => {
      const data = result.data;
      setCards(data);
    })

  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="page">
        <div className="container">
          
          <h1>Cards</h1>

          <div className={cardStyles.grid}>
            <div>iuiu</div>
            <div>iuiu</div>
            <div>iuiu</div>
            <div>iuiu</div>
            <div>iuiu</div>
            <div>iuiu</div>
          </div>

        </div>
      </div>

    </div>
  )
}
